version: '3'
services:
  headscale:
    image: headscale
    ports:
      - "8080:8080"
      - "3322:3322"
    volumes:
      - ./data:/root/.headscale
    environment:
      - HEADSCALE_LISTEN_PORT=3322
    restart: unless-stopped
