version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysql@123
    ports:
      - 3306:3306
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      - "./mysql/config.d:/etc/mysql/conf.d"
    restart: unless-stopped

