version: "3.3"
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysql@123
    ports:
      - 3306:3306
    volumes:
      - "../storage/mysql:/var/lib/mysql"
      - "./config.d:/etc/mysql/conf.d"
networks:
  default:
    external:
      name: aranoverse
