version: "3"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    network_mode: host
    ports:
      - "2181:2181"
    volumes:
      - ./zk:/bitnami/zookeeper #持久化数据
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    hostname: kafka
    network_mode: host
#    ports:
#      - "9004:9004"
    volumes:
      - ./kafka:/bitnami/kafka #持久化数据
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9004
#       KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9004 #替换成你自己的IP
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

