version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 198.19.249.3 #local ip
#      KAFKA_LISTENERS:
      KAFKA_CREATE_TOPICS: "topic_scanner_1,topic_indexer_1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    #    network_mode: host
#    network_mode: host
    ports:
      - 8080:8080
    #    volumes:
    #      - /home/ui-kafka/etc/localtime:/etc/localtime
    environment:
      # 集群名称
      - KAFKA_CLUSTERS_0_NAME=local
      # 集群地址
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 #替换成你自己的IP
      #    environment:
      #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #
    depends_on:
      - kafka