version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    network_mode: host
  #    ports:
#      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 #local ip
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
    network_mode: host
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    network_mode: host
#    ports:
#      - 8082:8080
    #    volumes:
    #      - /home/ui-kafka/etc/localtime:/etc/localtime
    environment:
      # 集群名称
      - KAFKA_CLUSTERS_0_NAME=kafka
      # 集群地址
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092 #替换成你自己的IP
      #    environment:
      #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #
    depends_on:
      - kafka