version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka #local ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - 8082:8080
    #    volumes:
    #      - /home/ui-kafka/etc/localtime:/etc/localtime
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 #替换成你自己的IP
      #    environment:
      #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #
    depends_on:
      - kafka