version: '3.3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - "./storage/postgres:/var/lib/postgresql"
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

