version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
      - ./enc_key_file:/dgraph/acl/hmac_secret_file
    ports:
      - 8666:8080
      - 9080:9080
    environment:
#      DGRAPH_ALPHA_ACL: secret-file=/dgraph/acl/hmac_secret_file
      #DGRAPH_ALPHA_SECURITY: whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16
      DGRAPH_ALPHA_SECURITY: whitelist=0.0.0.0/0
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080
  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
