version: "3.3"
services:
  redis:
    hostname: redis
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - "./storage/redis:/data"
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: redis-server --requirepass redis@123456


